# Generated by Django 4.2.5 on 2023-09-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('desc', models.TextField(verbose_name='Description')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_feedback', to='essay.feedback')),
            ],
            options={
                'verbose_name': 'Grammar',
                'verbose_name_plural': 'Grammar',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('desc', models.TextField(verbose_name='Description')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedback', to='essay.feedback')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('desc', models.TextField(verbose_name='Description')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_res_feedback', to='essay.feedback')),
            ],
            options={
                'verbose_name': 'Task Response',
                'verbose_name_plural': 'Task Responses',
            },
        ),
        migrations.CreateModel(
            name='ReportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sentence', models.TextField(verbose_name='Sentence')),
                ('word', models.TextField(verbose_name='Word')),
                ('notes', models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], max_length=125, verbose_name='Notes')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_answer', to='essay.report')),
            ],
            options={
                'verbose_name': 'Report Answer',
                'verbose_name_plural': 'Report Answers',
            },
        ),
        migrations.CreateModel(
            name='LexicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('desc', models.TextField(verbose_name='Description')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lex_check_feedback', to='essay.feedback')),
            ],
            options={
                'verbose_name': 'Lexical Check',
                'verbose_name_plural': 'Lexical Checks',
            },
        ),
        migrations.CreateModel(
            name='LexAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sentence', models.TextField(verbose_name='Sentence')),
                ('word', models.TextField(verbose_name='Word')),
                ('notes', models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], max_length=125, verbose_name='Notes')),
                ('lex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lex_answer', to='essay.lexicalcheck')),
            ],
            options={
                'verbose_name': 'Lexical Answer',
                'verbose_name_plural': 'Lexical Answers',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal')], max_length=55, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
        ),
        migrations.CreateModel(
            name='GrammarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sentence', models.TextField(verbose_name='Sentence')),
                ('word', models.TextField(verbose_name='Word')),
                ('notes', models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], max_length=125, verbose_name='Notes')),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_answer', to='essay.grammar')),
            ],
            options={
                'verbose_name': 'Grammar Answer',
                'verbose_name_plural': 'Grammar Answers',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_feedback', to='essay.letter'),
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_essays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essay',
                'verbose_name_plural': 'Essays',
            },
        ),
    ]
