# Generated by Django 4.2.5 on 2023-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='type',
            field=models.CharField(choices=[('Formal', 'Formal'), ('InFormal', 'InFormal')], max_length=125, verbose_name='Type'),
        ),
    ]
