# Generated by Django 4.2.5 on 2023-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_alter_letter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='cohesion',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Not Enough', 'Not Enough'), ('Good', 'Good')], max_length=55, null=True, verbose_name='Cohesion'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='sentence_variety',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Not Enough', 'Not Enough'), ('Good', 'Good')], max_length=55, null=True, verbose_name='Sentence Variety'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='cohesion',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Not Enough', 'Not Enough'), ('Good', 'Good')], max_length=55, null=True, verbose_name='Cohesion'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sentence_variety',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Not Enough', 'Not Enough'), ('Good', 'Good')], max_length=55, null=True, verbose_name='Sentence Variety'),
        ),
    ]
