# Generated by Django 4.2.5 on 2023-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_alter_essay_cohesion_alter_essay_sentence_variety_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='type',
            field=models.CharField(choices=[('formal', 'Formal'), ('informal', 'InFormal')], max_length=125, verbose_name='Type'),
        ),
    ]
