# Generated by Django 4.2.5 on 2023-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_alter_letter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='Json'),
        ),
    ]
