# Generated by Django 4.2.5 on 2023-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0006_remove_content_type_alter_content_main_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='main_type',
            field=models.CharField(blank=True, choices=[('Feedback', 'Feedback'), ('Grammar', 'Grammar'), ('Tone Feedback', 'Tone Feedback'), ('Lexical Resource', 'Lexical Resource'), ('Report', 'Report')], max_length=32, null=True, verbose_name='Main Type'),
        ),
    ]
