# Generated by Django 4.2.5 on 2023-09-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_status_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profile"},
        ),
    ]
