# Generated by Django 4.2.5 on 2023-09-26 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=55, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Extra Info",
                "verbose_name_plural": "Extra Infos",
            },
        ),
        migrations.CreateModel(
            name="SubScription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "FREE"),
                            ("PREMIUM 15", "PREMIUM 15"),
                            ("PREMIUM 25", "PREMIUM 25"),
                        ],
                        max_length=125,
                        verbose_name="Plan",
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=3, verbose_name="Coins")),
                ("price", models.PositiveIntegerField(verbose_name="Price")),
                (
                    "extra_info",
                    models.ManyToManyField(
                        related_name="subcription", to="subscription.extrainfo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
    ]
